apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      name: hello-world-job
    spec:
      completions: 1
      containers:
      - name: hello-world
        image: centos:7
        command:
         - "bin/bash"
         - "-c"
         - "echo hello world 2"
      restartPolicy: Never
